### PR TITLE
🐛 small grammar tweak

### PR DESCRIPTION
**Pull request by hlminh2000**

### CODE REVIEW

**Comment by alex-wilmer** [comment]
this pr doesn't add the plural either, so the grammar error will remain

**Comment by hlminh2000** [comment]
@alex-wilmer it was mentioned during the meeting that it should be "Showing 1 - 20 of 300 files", which I feel makes more sense https://github.com/kids-first/kf-portal-ui/issues/263

**Comment by alex-wilmer** [comment]
hmm this got merged but the plural mistake will remain

**Comment by jgnieuwhof** [comment]
@hlminh2000 - I thought you'd mentioned that it was now showing `files` rather than `file`?

**Comment by hlminh2000** [comment]
ah I was looking at the admin dashboard story and it looked fine, seems the component is used differently in the portal. I'll take a look

**Pull request merged**
