### PR TITLE
🦎 docusaurus

### PR DESCRIPTION
**Pull request by alex-wilmer**
possible future doc site?

### CODE REVIEW

**Comment by alex-wilmer** [comment]
https://docusaurus.io/

**Comment by alex-wilmer** [comment]
why close this? instead of people working on it

**Comment by alex-wilmer** [comment]
if youre going to close it, at least link to the issue which makes it irrelevant

**Comment by Fgerthoffert** [comment]
Closing this PR, some work will take place on documentation but likely not on docusaurus

**Pull request closed without merging**
