### PR TITLE
make use of "active" field on projects

### PR DESCRIPTION
**Pull request by alex-wilmer**
- Add general endpoint for modifying project fields
- if ES_HOST is provided as env, find active projects and "spin them up"
- default maximum number of "live" projects (only so many event listeners can be active by default)
- [😢] add integration test (i tried)

### CODE REVIEW

**Comment by alex-wilmer** [comment]
will add test after https://github.com/overture-stack/arranger/pull/205 gets merged

**Comment by Jephuff** [comment]
something weird is going on with the package-locks some are deleted?

**Comment by alex-wilmer** [comment]
okay I checked out the master version of lock files for packages i did not edit the package.json

**Comment by alex-wilmer** [comment]
i think i did a bad `lerna add` somewhere long the way

**Pull request merged**
