### PR TITLE
Table: allow checkbox off

### PR DESCRIPTION
**Pull request by cy**
need this for hcmi variant tables

### CODE REVIEW

**Comment by alex-wilmer** [comment]
`in`?!?! I was so confused reading this at first.

**Comment by alex-wilmer** [comment]
@Jephuff where do you stand on this?

**Comment by cy** [comment]
is the `in` part strange, I could use `defaultProps` instead? Trying not to break existing kidsfirst stuff

**Comment by Jephuff** [comment]
I would go with defaultProps :D 
Though... long term a better default might be no checkboxes. But thats not worth it now haha

**Comment by cy** [comment]
Thanks @Jephuff ! @alex-wilmer - i've updated with `defaultProps`, which i forgot about for a sec :sweat_smile:

**Pull request closed without merging**
